# Generated by Django 5.2 on 2025-04-23 15:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_input', models.TextField(blank=True, null=True, verbose_name='사용자 입력')),
                ('title', models.CharField(max_length=255, verbose_name='작업 제목')),
                ('details', models.TextField(blank=True, null=True, verbose_name='세부 계획/내용')),
                ('status', models.CharField(default='To Do', max_length=50, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('notion_page_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Notion 페이지 ID')),
            ],
            options={
                'verbose_name': '작업',
                'verbose_name_plural': '작업 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
